version: '3.7'

services:
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    environment:
      JAVA_TOOL_OPTIONS: -Xmx256m
      SERVER_PORT: 8080
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/txn_outbox
      SPRING_RABBITMQ_ADDRESSES: amqp://guest:guest@rabbit:5672
      SPRING_RABBITMQ_EXCHANGES_PREFIX: docker
      SPRING_RABBITMQ_QUEUES_PREFIX: docker
      LOGGING_LEVEL_DEV_HASHNODE_ISHBHANA: DEBUG
    ports:
      - "8080:8080"
    volumes:
      - ./docker/scripts:/usr/app/scripts:ro
    working_dir: /usr/app/
    entrypoint:
      - /bin/bash
      - ./scripts/wait-for-it.sh
      - mongo:27017
      - --timeout=40
      - --
      - /bin/bash
      - ./scripts/wait-for-it.sh
      - rabbit:5672
      - --timeout=40
      - --
      - java
      - -jar
      - order-service.jar

  mongo:
    image: mongo:5.0
    hostname: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: txn_outbox
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/initdb.d:/docker-entrypoint-initdb.d:ro

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: rabbit
    environment:
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"